[package]
name = "editor"
version = "0.1.0"
authors = ["simon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vulkano = "0.19.0"
vulkano-shaders = "0.19.0"
vulkano-win = "0.19.0"
winit = "0.22.2"
cgmath = "0.17"
glyph_brush = "0.7" 
glyph_brush_layout = "0.2.0"
glyph_brush_draw_cache = "0.1" 
image = "0.23.6"
