[package]
name = "editor"
version = "0.1.0"
authors = ["simon"]
edition = "2018"

[dependencies]
render = { path = "./render" }
eddy = { path = "./eddy" }
dirs = "3.0"
winit = "0.25"

[workspace]
members = ["render", "eddy"]
