[package]
name = "editor"
version = "0.1.0"
authors = ["simon"]
edition = "2018"

[dependencies]
render = { path = "./render" }
dirs = "3.0"
winit = "0.24"

[dependencies.glyph_brush]
version = "0.7"
default-features = false

[dependencies.scribe]
version = "0.7.2"
default-features = false

[workspace]
members = ["render"]
