[package]
name = "rpc"
version = "0.0.1"
authors = ["Simon Willshire"]

[lib]

[dependencies]
serde = "1.0.114"
serde_json = "1.0.57"

[dependencies.xi-core-lib]
version = "0.3.0"
default-features = false

[dependencies.xi-rpc]
version = "0.3.0"
default-features = false
