[package]
name = "render"
version = "0.1.0"
authors = ["Simon Willshire"]

[lib]

[dependencies]
vulkano = "0.20"
vulkano-win = "0.20"
vulkano-shaders = "0.20"

[dependencies.winit]
version = "0.24"
default-features = false
features=["wayland"]

[dependencies.glyph_brush]
version = "0.7"
default-features = false
