[package]
name = "render"
version = "0.1.0"
authors = ["Simon Willshire"]

[lib]

[dependencies]
vulkano = { git = "https://github.com/vulkano-rs/vulkano" }
vulkano-win = { git = "https://github.com/vulkano-rs/vulkano" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano" }

[dependencies.winit]
version = "0.24"
default-features = false
features=["wayland"]

[dependencies.glyph_brush]
version = "0.7.1"
default-features = false
