[package]
name = "render"
version = "0.1.0"
authors = ["Simon Willshire"]

[lib]

[dependencies]
vulkano = "0.19.0"
vulkano-win = "0.19.0"
vulkano-shaders = "0.19.0"

[dependencies.winit]
version = "0.22.2"
default-features = false

[dependencies.glyph_brush]
version = "0.7"
default-features = false
